import { useState, useMemo } from "react";

// ─── TYPES ────────────────────────────────────────────────────────────────────

interface Project {
  id: string;
  ticker: string;
  name: string;
  subtitle: string;
  category: "DIGITAL ART" | "PODCAST" | "FILM" | "MUSIC" | "LITERATURE";
  rarity: "EPIC" | "RARE" | "LEGENDARY" | "COMMON";
  lyaScore: number;          // /1000
  pricePerUnit: number;      // en USD (fluctue)
  revenueShare: number;      // %
  description: string;
  pitch: string;
  fundingRaised: number;
  fundingGoal: number;
  milestones: { label: string; done: boolean }[];
  gradient: string;          // classes Tailwind pour le fond de carte
}

// ─── DONNÉES PROJETS ──────────────────────────────────────────────────────────

const PROJECTS: Project[] = [
  {
    id: "chronos-v3",
    ticker: "LYA-CHRON",
    name: "CHRONOS_V3",
    subtitle: "ALGORITHMIC TEMPORAL GENERATIVE ART SYSTEM",
    category: "DIGITAL ART",
    rarity: "EPIC",
    lyaScore: 892,
    pricePerUnit: 57.20,
    revenueShare: 15,
    description:
      "A high-frequency algorithmic art generation system rendering continuous, high-fidelity visual streams. Revenue shares are distributed based on system performance milestones.",
    pitch:
      '"Chronos V3 tracks microscopic atmospheric pressure and global transaction volumes, translating them into perpetual, sublime vector graphics. Holding units lets you acquire the intellectual property streams generated by this node."',
    fundingRaised: 112500,
    fundingGoal: 150000,
    milestones: [
      { label: "Mainframe server integration completed", done: true },
      { label: "API access token distribution in June", done: false },
      { label: "Global visual exhibition in Paris", done: false },
    ],
    gradient: "from-[#6c3b9f] via-[#3b6fbf] to-[#1db8c4]",
  },
  {
    id: "future-voice",
    ticker: "LYA-FUTV",
    name: "THE FUTURE VOICE",
    subtitle: "PODCAST CO-PRODUCTION INITIATIVE",
    category: "PODCAST",
    rarity: "RARE",
    lyaScore: 840,
    pricePerUnit: 38.93,
    revenueShare: 12,
    description:
      "Top-tier podcast network. Significant drop in listener metrics and ad-revenue targets has severely impacted valuation.",
    pitch:
      '"The Future Voice is a distributed audio co-production platform. Unit holders receive proportional rights on ad-revenue and licensing fees generated across all syndicated episodes."',
    fundingRaised: 52210,
    fundingGoal: 85000,
    milestones: [
      { label: "Studio infrastructure deployed", done: true },
      { label: "Season 2 production launch", done: false },
      { label: "International distribution deal", done: false },
    ],
    gradient: "from-[#1a1a2e] via-[#16213e] to-[#0f3460]",
  },
  {
    id: "renaissance-reborn",
    ticker: "LYA-ART-REN",
    name: "RENAISSANCE REBORN",
    subtitle: "AI-POWERED CLASSICAL ART REIMAGINATION",
    category: "DIGITAL ART",
    rarity: "LEGENDARY",
    lyaScore: 960,
    pricePerUnit: 52.52,
    revenueShare: 18,
    description:
      "Award-winning digital art collection reimagining classical masterpieces through generative AI. Sharp post-release correction as initial demand stabilises.",
    pitch:
      '"Renaissance Reborn fuses 15th-century composition principles with neural rendering engines. Each unit grants fractional IP rights over the generated collection and future licensing revenues."',
    fundingRaised: 198000,
    fundingGoal: 250000,
    milestones: [
      { label: "Collection v1 minted and verified", done: true },
      { label: "Museum partnership agreement signed", done: true },
      { label: "Secondary market activation", done: false },
    ],
    gradient: "from-[#b45309] via-[#92400e] to-[#1c1917]",
  },
  {
    id: "quantum-realm",
    ticker: "LYA-QNTM",
    name: "QUANTUM REALM",
    subtitle: "SCIENTIFIC VISUALIZATION SERIES",
    category: "DIGITAL ART",
    rarity: "EPIC",
    lyaScore: 810,
    pricePerUnit: 49.18,
    revenueShare: 10,
    description:
      "Scientific visualization of probability fields. Revenue shares are tied to research publication licensing.",
    pitch:
      '"Quantum Realm renders quantum probability distributions as immersive visual art. Unit holders earn a share of licensing fees paid by research institutions and educational publishers."',
    fundingRaised: 67400,
    fundingGoal: 120000,
    milestones: [
      { label: "Physics lab collaboration established", done: true },
      { label: "First publication licensing deal", done: false },
      { label: "VR experience release", done: false },
    ],
    gradient: "from-[#0c4a6e] via-[#075985] to-[#0f172a]",
  },
];

// ─── THÈMES (EN ANGLAIS selon screenshot) ────────────────────────────────────

const THEMES = [
  { id: "all",        label: "All Masterpieces",      icon: "⭐", categories: null },
  { id: "visual",    label: "Visual Arts & Fashion",  icon: "🎨", categories: ["DIGITAL ART"] },
  { id: "cinema",    label: "Cinema & Narratives",    icon: "🎬", categories: ["FILM"] },
  { id: "music",     label: "Music & Concerts",       icon: "🎵", categories: ["MUSIC", "PODCAST"] },
  { id: "archi",     label: "Literature & Spaces",    icon: "🏛️", categories: ["LITERATURE"] },
];

// ─── COULEURS RARITY ─────────────────────────────────────────────────────────

const RARITY_COLORS: Record<string, string> = {
  EPIC:      "bg-purple-600 text-white",
  RARE:      "bg-cyan-500 text-black",
  LEGENDARY: "bg-amber-500 text-black",
  COMMON:    "bg-gray-500 text-white",
};

// ─── NIVEAUX MÉCÈNE ───────────────────────────────────────────────────────────

const PATRON_LEVELS = [
  {
    min: 1, max: 10,
    label: "ACTIVE PATRON",
    color: "text-cyan-400",
    desc: "Your name is immortalised in the LYA decentralised co-ownership register.",
  },
  {
    min: 11, max: 30,
    label: "GRAND PATRON LYA",
    color: "text-amber-400",
    desc: "Grand Collector level. Receive a signed physical art print and certified co-ownership rights.",
  },
  {
    min: 31, max: 60,
    label: "ELITE CO-OWNER",
    color: "text-purple-400",
    desc: "Elite Co-Owner level. VIP invitations to artwork galas, premium physical products and active voting rights.",
  },
  {
    min: 61, max: 100,
    label: "ELITE CO-OWNER",
    color: "text-purple-400",
    desc: "Elite Co-Owner level. VIP invitations to artwork galas, premium physical products and active voting rights.",
  },
];

function getPatronLevel(units: number) {
  return PATRON_LEVELS.find((l) => units >= l.min && units <= l.max) || PATRON_LEVELS[0];
}

// ─── MODAL PAIEMENT STRIPE ────────────────────────────────────────────────────

interface PaymentModalProps {
  project: Project;
  units: number;
  totalCost: number;
  onClose: () => void;
}

function PaymentModal({ project, units, totalCost, onClose }: PaymentModalProps) {
  const [email, setEmail] = useState("linkyourart@gmail.com");
  const [cardName, setCardName] = useState("");
  const [cardNumber, setCardNumber] = useState("");
  const [expiry, setExpiry] = useState("");
  const [cvv, setCvv] = useState("");

  const formatCard = (val: string) =>
    val.replace(/\D/g, "").slice(0, 16).replace(/(.{4})/g, "$1 ").trim();
  const formatExpiry = (val: string) =>
    val.replace(/\D/g, "").slice(0, 4).replace(/(.{2})/, "$1/");

  return (
    <div className="fixed inset-0 z-[100] bg-black/80 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-[#0d1117] border border-[#1e2a3a] rounded-2xl w-full max-w-md shadow-2xl">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-[#1e2a3a]">
          <div className="flex items-center gap-2">
            <span className="text-[#00ff88] text-sm">🔒</span>
            <span className="text-white font-mono text-sm tracking-widest">STRIPE SECURE CHECKOUT</span>
          </div>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-white w-7 h-7 flex items-center justify-center rounded border border-[#1e2a3a] hover:border-[#00d4ff] transition-colors"
          >
            ✕
          </button>
        </div>

        <div className="p-6 space-y-5">
          {/* Récap commande */}
          <div className="bg-[#1e2a3a]/40 rounded-xl p-4 flex justify-between items-start">
            <div>
              <p className="text-gray-500 text-xs font-mono mb-1">PATRONAGE PLEDGE:</p>
              <p className="text-white font-bold font-mono italic">{project.name}</p>
              <p className="text-gray-400 text-xs font-mono mt-1">
                {units} units supported × ${project.pricePerUnit.toFixed(2)}
              </p>
            </div>
            <div className="text-right">
              <p className="text-gray-500 text-xs font-mono mb-1">TOTAL COST</p>
              <p className="text-[#00ff88] font-bold text-2xl font-mono">${totalCost.toFixed(2)}</p>
            </div>
          </div>

          {/* Email */}
          <div>
            <label className="text-gray-400 text-xs font-mono tracking-widest block mb-2">
              BILLING EMAIL ADDRESS
            </label>
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="w-full bg-[#1a2233] border border-[#1e2a3a] rounded-lg px-4 py-3 text-white font-mono text-sm focus:border-[#00d4ff] focus:outline-none transition-colors"
            />
          </div>

          {/* Nom */}
          <div>
            <label className="text-gray-400 text-xs font-mono tracking-widest block mb-2">
              CARDHOLDER NAME
            </label>
            <input
              type="text"
              value={cardName}
              onChange={(e) => setCardName(e.target.value)}
              placeholder="JANE DOE"
              className="w-full bg-[#1a2233] border border-[#1e2a3a] rounded-lg px-4 py-3 text-white font-mono text-sm placeholder-gray-600 focus:border-[#00d4ff] focus:outline-none transition-colors"
            />
          </div>

          {/* Numéro de carte + logos */}
          <div>
            <label className="text-gray-400 text-xs font-mono tracking-widest block mb-2">
              CARD CREDENTIALS
            </label>
            <div className="relative">
              <input
                type="text"
                value={cardNumber}
                onChange={(e) => setCardNumber(formatCard(e.target.value))}
                placeholder="4242 4242 4242 4242"
                maxLength={19}
                className="w-full bg-[#1a2233] border border-[#1e2a3a] rounded-lg px-4 py-3 text-white font-mono text-sm placeholder-gray-600 focus:border-[#00d4ff] focus:outline-none transition-colors pr-36"
              />
              {/* Logos cartes */}
              <div className="absolute right-3 top-1/2 -translate-y-1/2 flex items-center gap-1">
                {/* VISA */}
                <span className="bg-[#1a1f71] text-white text-[10px] font-bold px-2 py-0.5 rounded font-sans italic">VISA</span>
                {/* MC */}
                <span className="flex">
                  <span className="w-4 h-4 rounded-full bg-[#eb001b] opacity-90 -mr-1.5" />
                  <span className="w-4 h-4 rounded-full bg-[#f79e1b] opacity-90" />
                </span>
                {/* AMEX */}
                <span className="bg-[#2557d6] text-white text-[9px] font-bold px-1.5 py-0.5 rounded font-sans">AMEX</span>
                {/* CB */}
                <span className="bg-[#00a1e0] text-white text-[10px] font-bold px-1.5 py-0.5 rounded font-sans">CB</span>
              </div>
            </div>
          </div>

          {/* Expiry + CVV */}
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="text-gray-400 text-xs font-mono tracking-widest block mb-2">
                EXPIRY DATE
              </label>
              <input
                type="text"
                value={expiry}
                onChange={(e) => setExpiry(formatExpiry(e.target.value))}
                placeholder="MM/YY"
                maxLength={5}
                className="w-full bg-[#1a2233] border border-[#1e2a3a] rounded-lg px-4 py-3 text-white font-mono text-sm placeholder-gray-600 focus:border-[#00d4ff] focus:outline-none transition-colors"
              />
            </div>
            <div>
              <label className="text-gray-400 text-xs font-mono tracking-widest block mb-2">
                CVV CODE
              </label>
              <input
                type="password"
                value={cvv}
                onChange={(e) => setCvv(e.target.value.replace(/\D/g, "").slice(0, 4))}
                placeholder="•••"
                maxLength={4}
                className="w-full bg-[#1a2233] border border-[#1e2a3a] rounded-lg px-4 py-3 text-white font-mono text-sm placeholder-gray-600 focus:border-[#00d4ff] focus:outline-none transition-colors"
              />
            </div>
          </div>

          {/* Bouton payer */}
          <button className="w-full bg-[#00ff88] hover:bg-[#00cc66] text-black font-bold font-mono py-4 rounded-xl transition-colors text-sm tracking-widest">
            ✦ CONFIRM PATRONAGE — ${totalCost.toFixed(2)}
          </button>

          <p className="text-center text-gray-600 text-xs font-mono">
            Secured by Stripe · EU MiCA compliant · LYA Ledger registered
          </p>
        </div>
      </div>
    </div>
  );
}

// ─── MODAL DÉTAIL PROJET ──────────────────────────────────────────────────────

interface ProjectDetailModalProps {
  project: Project;
  units: number;
  onClose: () => void;
  onPay: () => void;
}

function ProjectDetailModal({ project, units, onClose, onPay }: ProjectDetailModalProps) {
  const totalCost = units * project.pricePerUnit;
  const revenueRights = ((units * project.revenueShare) / 10000).toFixed(3);
  const fundingPct = Math.round((project.fundingRaised / project.fundingGoal) * 100);

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-[#0d1117] border border-[#1e2a3a] rounded-2xl w-full max-w-4xl max-h-[90vh] overflow-y-auto shadow-2xl">
        <div className="grid grid-cols-1 lg:grid-cols-2">
          {/* Colonne gauche — visuels */}
          <div className="p-6 border-b lg:border-b-0 lg:border-r border-[#1e2a3a]">
            {/* Badge galerie */}
            <div className="flex items-center gap-2 mb-4">
              <span className="text-[#00d4ff] text-xs">🖼</span>
              <span className="text-[#00d4ff] text-xs font-mono tracking-widest border border-[#00d4ff]/30 px-3 py-1 rounded">
                ART PROJECT GALLERY
              </span>
            </div>

            {/* Image principale */}
            <div className={`rounded-xl aspect-video bg-gradient-to-br ${project.gradient} mb-3 flex items-center justify-center`}>
              <span className="text-white/20 font-mono text-xs">{project.ticker}</span>
            </div>

            {/* Thumbnails */}
            <div className="flex gap-2 mb-5">
              {[0, 1, 2].map((i) => (
                <div
                  key={i}
                  className={`flex-1 aspect-video rounded-lg bg-gradient-to-br ${project.gradient} opacity-${i === 0 ? "100" : i === 1 ? "60" : "30"} border-2 ${i === 0 ? "border-[#00d4ff]" : "border-transparent"} cursor-pointer`}
                />
              ))}
            </div>

            {/* LYA Compliance */}
            <div className="bg-[#0a1628] border border-[#1e2a3a] rounded-xl p-4">
              <div className="flex items-center gap-2 mb-2">
                <span className="text-[#00ff88] text-sm">✓</span>
                <span className="text-[#00ff88] text-xs font-mono tracking-widest">LYA COMPLIANCE ASSURANCE</span>
              </div>
              <p className="text-gray-400 text-xs mb-3">
                Audited and verified by Warner Music Hub under EU MiCA guidelines. Smart contract addresses are permanently etched on the LYA register.
              </p>
              <div className="flex gap-3">
                <span className="border border-[#1e2a3a] text-gray-400 text-xs font-mono px-3 py-1 rounded">
                  Jurisdiction: EU (MiCA)
                </span>
                <span className="border border-[#1e2a3a] text-gray-400 text-xs font-mono px-3 py-1 rounded">
                  Ledger: LYA_REG_0x71C4F2A
                </span>
              </div>
            </div>
          </div>

          {/* Colonne droite — infos */}
          <div className="p-6">
            {/* Header */}
            <div className="flex justify-between items-start mb-4">
              <div>
                <div className="flex items-center gap-2 mb-2">
                  <span className="bg-[#1e2a3a] text-[#00d4ff] text-xs font-mono px-2 py-1 rounded">
                    {project.category}
                  </span>
                  <span className="text-gray-500 text-xs font-mono">ID: {project.id.toUpperCase()}</span>
                </div>
                <h2 className="text-white font-black text-2xl font-mono italic mb-1">{project.name}</h2>
                <p className="text-[#00d4ff] text-xs font-mono tracking-widest">{project.subtitle}</p>
              </div>
              <button
                onClick={onClose}
                className="w-9 h-9 rounded-full border border-[#1e2a3a] flex items-center justify-center text-gray-400 hover:text-white hover:border-[#00d4ff] transition-colors"
              >
                ✕
              </button>
            </div>

            {/* Financement */}
            <div className="mb-5">
              <div className="flex justify-between items-center mb-1">
                <span className="text-gray-500 text-xs font-mono">TARGET PROJECT BUDGET</span>
                <span className="text-[#00ff88] text-xs font-mono font-bold">{fundingPct}%</span>
              </div>
              <div className="w-full bg-[#1e2a3a] rounded-full h-1.5 mb-1">
                <div
                  className="bg-[#00ff88] h-1.5 rounded-full"
                  style={{ width: `${fundingPct}%` }}
                />
              </div>
              <div className="flex justify-between text-xs font-mono text-gray-500">
                <span>RAISED AMOUNT: ${project.fundingRaised.toLocaleString()}.00</span>
                <span>GLOBAL GOAL: ${project.fundingGoal.toLocaleString()}.00</span>
              </div>
            </div>

            {/* Pitch */}
            <div className="mb-5">
              <p className="text-gray-500 text-xs font-mono tracking-widest mb-2">PROJECT PITCH & SYNOPSIS</p>
              <p className="text-gray-300 text-sm italic border-l-2 border-[#00d4ff]/30 pl-3">
                {project.pitch}
              </p>
            </div>

            {/* Milestones */}
            <div className="mb-5">
              <p className="text-gray-500 text-xs font-mono tracking-widest mb-3">DEVELOPMENT MILESTONES</p>
              <div className="space-y-2">
                {project.milestones.map((m, i) => (
                  <div key={i} className="flex items-center gap-2">
                    <span className={`w-4 h-4 rounded-full flex items-center justify-center text-xs ${m.done ? "bg-[#00ff88]/20 text-[#00ff88]" : "border border-[#1e2a3a] text-gray-600"}`}>
                      {m.done ? "✓" : "○"}
                    </span>
                    <span className={`text-xs font-mono ${m.done ? "text-gray-500 line-through" : "text-gray-300"}`}>
                      {m.label}
                    </span>
                  </div>
                ))}
              </div>
            </div>

            {/* Bénéfices estimés */}
            <div className="bg-[#0a1628] border border-[#1e2a3a] rounded-xl p-4 mb-5">
              <p className="text-gray-500 text-xs font-mono tracking-widest mb-3">
                ESTIMATED BENEFITS FOR: {units} UNITS SUPPORTING
              </p>
              <div className="flex justify-between items-center mb-1">
                <span className="text-gray-400 text-sm">Total backing pledge:</span>
                <span className="text-white font-mono font-bold">${totalCost.toFixed(2)}</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-gray-400 text-sm">Cumulative Revenue rights:</span>
                <span className="text-[#00ff88] font-mono font-bold">{revenueRights}%</span>
              </div>
              <p className="text-gray-600 text-xs mt-3">
                * Note: Support pledge proceeds are securely held in trust. Benefits triggering aligns automatically with validated milestone release dates.
              </p>
            </div>

            {/* Bouton payer */}
            <button
              onClick={onPay}
              className="w-full bg-[#00ff88] hover:bg-[#00cc66] text-black font-bold font-mono py-4 rounded-xl transition-colors text-sm tracking-widest"
            >
              ✦ SUPPORT THIS PROJECT — ${totalCost.toFixed(2)}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

// ─── CARD PROJET ──────────────────────────────────────────────────────────────

interface ProjectCardProps {
  project: Project;
  onOpenDetail: (project: Project, units: number) => void;
}

function ProjectCard({ project, onOpenDetail }: ProjectCardProps) {
  const [units, setUnits] = useState(5);
  const [liked, setLiked] = useState(false);

  const totalCost = units * project.pricePerUnit;
  const coShare = ((units * project.revenueShare) / 10000).toFixed(3);
  const level = getPatronLevel(units);
  const fundingPct = Math.round((project.fundingRaised / project.fundingGoal) * 100);

  return (
    <div className="bg-[#0d1117] border border-[#1e2a3a] rounded-2xl overflow-hidden flex flex-col">

      {/* ── Visuel carte ───────────────────────────────────────────────────── */}
      <div
        className={`relative bg-gradient-to-br ${project.gradient} aspect-video flex items-end p-4 cursor-pointer`}
        onClick={() => onOpenDetail(project, units)}
      >
        {/* Badges haut gauche */}
        <div className="absolute top-3 left-3 flex flex-col gap-1.5">
          <span className="bg-[#0d1117]/80 text-[#00d4ff] text-xs px-2 py-0.5 rounded font-mono w-fit">
            {project.category}
          </span>
          <span className="bg-amber-500 text-black text-xs px-2 py-0.5 rounded font-mono font-bold w-fit flex items-center gap-1">
            ★ LYA SCORE: {project.lyaScore}
          </span>
          <span className={`text-xs px-2 py-0.5 rounded font-mono font-bold w-fit ${RARITY_COLORS[project.rarity]}`}>
            {project.rarity}
          </span>
        </div>

        {/* Like */}
        <button
          onClick={(e) => { e.stopPropagation(); setLiked(!liked); }}
          className={`absolute top-3 right-3 w-8 h-8 rounded-full bg-[#0d1117]/60 flex items-center justify-center transition-colors ${liked ? "text-red-500" : "text-gray-400 hover:text-red-400"}`}
        >
          ♥
        </button>

        {/* Infos bas */}
        <div className="w-full">
          <p className="text-xs text-gray-400 font-mono mb-1">CREATIVE VENTURE</p>
          <div className="flex justify-between items-end">
            <h3 className="text-white font-black text-lg font-mono italic">{project.name}</h3>
            <div className="text-right">
              <p className="text-white text-sm font-mono">${project.pricePerUnit.toFixed(2)} / Unit</p>
              <p className="text-[#00ff88] text-xs font-mono">{project.revenueShare}% Revenue Rights</p>
            </div>
          </div>
        </div>
      </div>

      {/* ── Description + sous-titre ────────────────────────────────────────── */}
      <div className="px-5 pt-4 pb-3 border-b border-[#1e2a3a]">
        <p className="text-[#00d4ff] text-xs font-mono tracking-widest mb-1">{project.subtitle}</p>
        <p className="text-gray-400 text-sm">{project.description}</p>
      </div>

      {/* ── LYA Quality Score + Funding ─────────────────────────────────────── */}
      <div className="px-5 py-4 border-b border-[#1e2a3a] space-y-3">
        {/* Score */}
        <div className="flex items-center justify-between">
          <span className="text-gray-500 text-xs font-mono flex items-center gap-1">
            ★ LYA QUALITY SCORE
          </span>
          <span className="text-amber-400 font-mono font-bold">
            {project.lyaScore} <span className="text-gray-600 font-normal">/ 1000</span>
          </span>
        </div>
        <div className="w-full bg-[#1e2a3a] rounded-full h-0.5">
          <div
            className="bg-amber-400 h-0.5 rounded-full"
            style={{ width: `${(project.lyaScore / 1000) * 100}%` }}
          />
        </div>

        {/* Funding */}
        <div>
          <div className="flex justify-between items-center mb-1">
            <span className="text-gray-500 text-xs font-mono">FUNDING PROGRESS</span>
            <span className="text-[#00ff88] text-xs font-mono font-bold">{fundingPct}%</span>
          </div>
          <div className="w-full bg-[#1e2a3a] rounded-full h-1.5 mb-1">
            <div
              className="bg-[#00ff88] h-1.5 rounded-full"
              style={{ width: `${fundingPct}%` }}
            />
          </div>
          <div className="flex justify-between text-xs font-mono text-gray-600">
            <span>${project.fundingRaised.toLocaleString()}.00</span>
            <span>Goal: ${project.fundingGoal.toLocaleString()}.00</span>
          </div>
        </div>
      </div>

      {/* ── Curseur interactif ───────────────────────────────────────────────── */}
      <div className="px-5 py-4 space-y-3">
        <div className="flex justify-between items-center">
          <span className="text-white text-xs font-mono font-bold tracking-widest">LYA UNITS ACQUISITION VOLUME</span>
          <span className="bg-[#1e2a3a] text-[#00d4ff] text-xs px-3 py-1 rounded font-mono">
            {units} Units Supporting
          </span>
        </div>

        <input
          type="range"
          min={1}
          max={100}
          value={units}
          onChange={(e) => setUnits(Number(e.target.value))}
          className="w-full h-1 bg-[#1e2a3a] rounded-full appearance-none cursor-pointer accent-[#00d4ff]"
        />

        <div className="flex justify-between text-xs text-gray-600 font-mono">
          <span>MIN (1 UNIT)</span>
          <span>CURATOR (50)</span>
          <span>MAX (100 UNITS)</span>
        </div>

        <div className="grid grid-cols-2 gap-3">
          <div className="bg-[#1e2a3a]/50 rounded-lg p-3">
            <p className="text-gray-500 text-xs font-mono mb-1">YOUR PLEDGE</p>
            <p className="text-white font-bold font-mono">${totalCost.toFixed(2)}</p>
          </div>
          <div className="bg-[#1e2a3a]/50 rounded-lg p-3">
            <p className="text-gray-500 text-xs font-mono mb-1">REVENUE CO-SHARE</p>
            <p className="text-[#00ff88] font-bold font-mono">{coShare}%</p>
          </div>
        </div>

        {/* Niveau */}
        <div className="border border-[#1e2a3a] rounded-lg p-3">
          <p className={`text-xs font-mono font-bold mb-1 ${level.color}`}>{level.label}</p>
          <p className="text-gray-400 text-xs">{level.desc}</p>
        </div>

        <div className="grid grid-cols-2 gap-3">
          <button
            onClick={() => onOpenDetail(project, units)}
            className="border border-[#1e2a3a] text-white py-3 rounded-xl font-mono text-xs hover:border-[#00d4ff] transition-colors tracking-wider"
          >
            GRAND REGISTER
          </button>
          <button
            onClick={() => onOpenDetail(project, units)}
            className="bg-[#00ff88] text-black py-3 rounded-xl font-mono text-xs font-bold hover:bg-[#00cc66] transition-colors flex items-center justify-center gap-1 tracking-wider"
          >
            ✦ SUPPORT PROJECT
          </button>
        </div>
      </div>
    </div>
  );
}

// ─── SECTION "WHAT IS THE LYA UNIT?" ─────────────────────────────────────────

function WhatIsLyaUnit() {
  return (
    <div className="bg-[#0a1628] border border-[#1e2a3a] rounded-2xl p-6 grid grid-cols-1 md:grid-cols-4 gap-6">
      <div>
        <p className="text-gray-500 text-xs font-mono tracking-widest mb-2">OFFICIAL DEFINITION</p>
        <h3 className="text-white font-black text-xl leading-tight">WHAT IS THE LYA UNIT?</h3>
        <div className="w-8 h-0.5 bg-[#00d4ff] mt-2" />
      </div>
      <div>
        <p className="text-[#00d4ff] text-xs font-mono tracking-widest mb-2">01. EVOLUTIONARY MEASURE</p>
        <p className="text-gray-300 text-sm">
          It is the official quotation unit that measures the evolutionary value of a creation.
        </p>
      </div>
      <div>
        <p className="text-[#00d4ff] text-xs font-mono tracking-widest mb-2">02. NOT A CRYPTO</p>
        <p className="text-gray-300 text-sm">
          It is NOT a classic currency or a crypto.
        </p>
      </div>
      <div>
        <p className="text-[#00d4ff] text-xs font-mono tracking-widest mb-2">03. STRUCTURED STATE</p>
        <p className="text-gray-300 text-sm">
          It is a structured unit of value that represents the real state, solidity, and trajectory of a creation.
        </p>
      </div>
    </div>
  );
}

// ─── COMPOSANT PRINCIPAL ──────────────────────────────────────────────────────

export function MecenatGrandPublic() {
  const [activeTheme, setActiveTheme] = useState("all");
  const [detailProject, setDetailProject] = useState<{ project: Project; units: number } | null>(null);
  const [showPayment, setShowPayment] = useState(false);

  const filteredProjects = useMemo(() => {
    const theme = THEMES.find((t) => t.id === activeTheme);
    if (!theme || !theme.categories) return PROJECTS;
    return PROJECTS.filter((p) => theme.categories!.includes(p.category));
  }, [activeTheme]);

  return (
    <section className="bg-[#080c10] min-h-screen">

      {/* ── Header ──────────────────────────────────────────────────────────── */}
      <div className="px-6 py-10 max-w-7xl mx-auto">
        <div className="flex items-center gap-2 mb-6">
          <span className="text-[#00d4ff] text-xs font-mono">✦</span>
          <span className="text-[#00d4ff] text-xs font-mono tracking-widest border border-[#00d4ff]/30 px-3 py-1 rounded-full">
            LYA PATRONAGE HUB
          </span>
        </div>

        <div className="flex flex-col lg:flex-row justify-between items-start gap-8 mb-10">
          <div>
            <h1 className="text-4xl lg:text-5xl font-black text-white leading-tight mb-4">
              CO-OWN TOMORROW'S<br />MASTERPIECES IN ONE CLICK
            </h1>
            <p className="text-gray-400 max-w-xl text-sm">
              Welcome to our simplified discovery space. No financial charts or intimidating order books.
              Just sublime art, raw talent, and a simple interactive way to support your favourite
              creators and share in their future success.
            </p>
          </div>
          <div className="bg-[#0d1117] border border-[#1e2a3a] rounded-2xl p-6 min-w-[200px] text-center shrink-0">
            <p className="text-gray-500 text-xs font-mono mb-2">FOUNDING FIXED VALUE</p>
            <p className="text-white text-2xl font-bold font-mono">
              1 Unit = <span className="text-[#00d4ff]">$50.00</span>
            </p>
            <div className="mt-3 bg-[#00ff88] text-black text-xs font-mono font-bold px-4 py-2 rounded-lg">
              ACCESSIBLE TO ALL
            </div>
          </div>
        </div>

        {/* ── Filtres thématiques ──────────────────────────────────────────── */}
        <div className="mb-8">
          <p className="text-[#00d4ff] text-xs font-mono tracking-widest mb-4">
            ● CHOOSE AN ART MOOD
          </p>
          <div className="flex flex-wrap gap-3">
            {THEMES.map((theme) => (
              <button
                key={theme.id}
                onClick={() => setActiveTheme(theme.id)}
                className={`flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-mono transition-all ${
                  activeTheme === theme.id
                    ? "bg-[#00d4ff] text-black font-bold"
                    : "border border-[#1e2a3a] text-gray-400 hover:border-[#00d4ff]/50"
                }`}
              >
                <span>{theme.icon}</span>
                {theme.label}
              </button>
            ))}
          </div>
        </div>

        {/* ── Section LYA Unit ────────────────────────────────────────────── */}
        <WhatIsLyaUnit />
      </div>

      {/* ── Grille projets ──────────────────────────────────────────────────── */}
      <div className="px-6 pb-16 max-w-7xl mx-auto">
        {filteredProjects.length === 0 ? (
          <div className="text-center py-20 text-gray-600 font-mono">
            No projects in this category yet.
          </div>
        ) : (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {filteredProjects.map((project) => (
              <ProjectCard
                key={project.id}
                project={project}
                onOpenDetail={(p, u) => setDetailProject({ project: p, units: u })}
              />
            ))}
          </div>
        )}
      </div>

      {/* ── Modal détail ────────────────────────────────────────────────────── */}
      {detailProject && !showPayment && (
        <ProjectDetailModal
          project={detailProject.project}
          units={detailProject.units}
          onClose={() => setDetailProject(null)}
          onPay={() => setShowPayment(true)}
        />
      )}

      {/* ── Modal paiement ──────────────────────────────────────────────────── */}
      {detailProject && showPayment && (
        <PaymentModal
          project={detailProject.project}
          units={detailProject.units}
          totalCost={detailProject.units * detailProject.project.pricePerUnit}
          onClose={() => { setShowPayment(false); setDetailProject(null); }}
        />
      )}
    </section>
  );
}

export default MecenatGrandPublic;
